server {
    listen 443 ssl;
    listen [::]:443 ssl;
<<<<<<< HEAD

    server_name rmarrero.42.fr;

    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;

=======
    server_name rmarrero.42.fr;
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;
>>>>>>> 108efd410ac074d0350685da81ec1244b40391c1
    root /var/www/html;
    index index.php index.html index.htm;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
<<<<<<< HEAD
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
=======
        include snippets/fastcgi-php.conf;
>>>>>>> 108efd410ac074d0350685da81ec1244b40391c1
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}