name: rmarrero/inception:latest
version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inception_db
      MYSQL_USER: inception_user
      MYSQL_PASSWORD: inception_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    build: ./adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080